CREATE TABLE IF NOT EXISTS QUIZZES (
    id BIGSERIAL PRIMARY KEY,
    category_id BIGINT NOT NULL,
    creator BIGINT NOT NULL,
    is_finished BOOLEAN DEFAULT FALSE,
    started_at TIMESTAMP(0) WITH TIME ZONE,
    finished_at TIMESTAMP(0) WITH TIME ZONE,
    FOREIGN KEY (creator) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES CATEGORIES (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUIZZES_QUESTIONS (
    quiz_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    PRIMARY KEY (quiz_id, question_id),
    FOREIGN KEY (quiz_id) REFERENCES QUIZZES (id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES QUESTIONS (id) ON DELETE CASCADE
);