CREATE TABLE IF NOT EXISTS ANSWERS (
    id          BIGSERIAL PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    quiz_id     BIGINT NOT NULL,
    answered_at TIMESTAMP(0) WITH TIME ZONE,
    rating      INT2 NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_id) REFERENCES QUIZZES (id) ON DELETE CASCADE
)